# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# [general]
font_size 16.0

# [window]
tab_bar_min_tabs 1
# {fmt.fg.red} 是设置高亮颜色，{fmt.fg.tab} 是恢复默认色
# title.split()[0] 是只取当前目录的最后一个文件夹名，保持简短
tab_title_template "{index}: {title.split('/')[-1]} {num_windows > 1 and f'[{num_windows}]' or ''}"
active_tab_title_template "{fmt.fg.red}{index}: {title.split('/')[-1]}{fmt.fg.tab} {num_windows > 1 and f'[{num_windows}]' or ''}"

# [keymap]
copy_on_select yes
map ctrl+v paste_from_clipboard
# [keymap.tab]
map alt+n new_tab
map alt+[ previous_tab
map alt+] next_tab
map alt+shift+[ move_tab_backward
map alt+shift+] move_tab_forward
# [keymap.window]
map alt+= new_window_with_cwd
map alt+- close_window
# [keymap.size]
map ctrl+equal  change_font_size all +2.0
map ctrl+minus  change_font_size all -2.0
map ctrl+0      change_font_size all 0
# [keymap.pane]
map alt+left  neighboring_window left
map alt+right neighboring_window right
map alt+up    neighboring_window up
map alt+down  neighboring_window down
