# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# [font]
font_size 16.0
font_family      family="Monaspace Neon NF"
bold_font        auto
italic_font      auto
bold_italic_font auto
# [window]
tab_bar_min_tabs 1
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
# tab_bar_style slant
# tab_bar_style separator
# tab_separator " "
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{index}:{title}"

# [keymap]
copy_on_select yes
map ctrl+v paste_from_clipboard
# [keymap.tab]
map alt+n new_tab
map alt+[ previous_tab
map alt+] next_tab
map alt+shift+[ move_tab_backward
map alt+shift+] move_tab_forward
# [keymap.window]
map alt+= new_window_with_cwd
map alt+- close_window
# [keymap.size]
map ctrl+equal  change_font_size all +2.0
map ctrl+minus  change_font_size all -2.0
map ctrl+0      change_font_size all 0
# [keymap.pane]
map alt+left  neighboring_window left
map alt+right neighboring_window right
map alt+up    neighboring_window up
map alt+down  neighboring_window down
# [mouse]
# mouse_map ctrl+left release grabbed,ungrabbed mouse_handle_click link
