[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[font]
size = 14.0

[window]
decorations = "full"
# padding = { x = 12, y = 12 }
opacity = 0.9
dimensions = { columns = 120, lines = 35 }

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[bell]
duration = 0

[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste" },
  { key = "Enter", mods = "Shift", chars = "\n" },
]
