[general]
import = [
  "~/.config/alacritty/dank-theme.toml"
]

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[window]
decorations = "full"
padding = { x = 12, y = 12 }
opacity = 1.0
dimensions = { columns = 120, lines = 35 }

[scrolling]
history = 3023

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = true

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[bell]
duration = 0

[keyboard]
bindings = [
  { key = "C",       mods = "Control", action = "Copy"  },
  { key = "V",       mods = "Control", action = "Paste" },
  { key = "N",       mods = "Control", action = "SpawnNewInstance" },
  { key = "Equals",  mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus",   mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",    mods = "Control",       action = "ResetFontSize"    },
  { key = "Enter",   mods = "Shift",         chars = "\n" },
]
